name: DJE Scraper Schedule

on:
  schedule:
    - cron: '0 8,14,18 * * *'  # 08:00, 14:00, 18:00 UTC (05:00, 11:00, 15:00 BRT)
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('scraper/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      working-directory: ./scraper
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      working-directory: ./scraper
      env:
        API_URL: ${{ secrets.API_URL }}
        RUN_ONCE: true
      run: |
        python main.py
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: 1,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚨 Scraper falhou na execução agendada em ' + new Date().toISOString()
          }) 